### PR TITLE
Update Message.js

### PR DESCRIPTION
**Pull request by seba-salavilla**

### CODE REVIEW

**Review by MaybeRex — APPROVED** [review]
ty

**Comment by MaybeRex** [comment]
@seba-salavilla why close the PR? should have merged it

**Comment by MaybeRex** [comment]
@RIAEvangelist can you merge this and do a version release?

**Comment by seba-salavilla** [comment]
i can't merged...

**Comment by RIAEvangelist** [comment]
When my plane lands I'll give it a shot.

**Comment by RIAEvangelist** [comment]
very long plane ride

**Pull request merged**
